title: "天空的安静"
author: "孙立杰"
description: "anything interesting"
#subheading: "Really cool blog about ... something"
more: "read more"
url: ""
baseurl: "" # comment out if in root directory

comments:
    disqus: "skyquiet"
    #isso: "comments.mysite.org"
    isso: "skyquiet.github.io"

style:
#    body: "whitesmoke"
    padding: 33%
    anchor: "#46f"
    serif-heading: true
    nav: "#181818"
#    headline: "#06f"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#222222"

links:
  - github: "https://github.com/skyquiet"
  - twitter: "https://twitter.com/SkyQuiet"
#  - google-plus: "https://plus.google.com/+me"
#  - reddit: "https://www.reddit.com"
#  - youtube: "https://www.youtube.com/user/me"
#  - steam: "http://steamcommunity.com/id/me/"

excerpt_separator: "\n\n\n"
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
